### PR TITLE
Changed Somethings Added Game Status , Multi Prefix

### PR DESCRIPTION
**Pull request by SARP4**

### CODE REVIEW

**Comment by Habchy** [comment]
Please fix the one error and redo a pull request, thanks man.

**Comment by SarpTurker** [comment]
İ tested The code it worked with no error

**Comment by SARP4** [comment]
[BasicBot.zip](https://github.com/Habchy/BasicBot/files/1485451/BasicBot.zip)
**Fixed Error file on up**

**Comment by Habchy** [comment]
thanks, will be in version 2.1 👍

**Pull request closed without merging**
